services:
  - type: web
    name: tharik-ai-gpt-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: SERVE_FRONTEND
        value: "false"
      - key: AUTO_RUN_FRONTEND
        value: "false"
      - key: CORS_ORIGINS
        value: "https://tharikai.netlify.app"
