import { jsPDF } from "jspdf";
import * as XLSX from "xlsx";
import JSZip from "jszip";
import pptxgen from "pptxgenjs";
import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  Table,
  TableRow,
  TableCell,
  WidthType,
  BorderStyle,
  AlignmentType,
  ShadingType,
  Footer,
  PageNumber,
} from "docx";

/**
 * Standard trigger to download blob in browser
 */
export function triggerDownload(blob, filename) {
  const url = window.URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => window.URL.revokeObjectURL(url), 1000);
}

/**
 * Download raw text or code file (e.g. script.py, index.html, styles.css)
 */
export function downloadTextFile(filename, content, mimeType = "text/plain;charset=utf-8") {
  const blob = new Blob([content], { type: mimeType });
  triggerDownload(blob, filename);
}

/**
 * Clean document text: strip web citation URLs, raw brackets, and template metadata
 */
export function cleanDocumentText(text) {
  if (!text) return "";
  return text
    // Remove markdown image tags ![alt](url)
    .replace(/!\[.*?\]\(.*?\)/g, "")
    // Remove web search citation links: [1](https://...), [2](https://...)
    .replace(/\[\d+\]\([^)]+\)/g, "")
    // Remove citation numbers in brackets: [1], [2], [12]
    .replace(/\[\d+\]/g, "")
    // Remove markdown links but preserve the readable anchor text: [Anchor](url) -> Anchor
    .replace(/\[([^\]]+)\]\([^)]+\)/g, "$1")
    // Remove standalone URLs
    .replace(/https?:\/\/[^\s)]+/g, "")
    // Remove template metadata lines
    .replace(/^(?:Executive\s+)?Document:\s*.*$/gim, "")
    .replace(/^Date:\s*.*$/gim, "")
    .replace(/^Prepared\s+by:\s*.*$/gim, "")
    .replace(/^Author:\s*.*$/gim, "")
    .replace(/^[-*_]{3,}$/gm, "")
    .trim();
}

/**
 * Clean markdown symbols for clean document text export
 */
export function cleanMarkdownForDoc(text) {
  if (!text) return "";
  return cleanDocumentText(text)
    .replace(/^#+\s+/gm, "") // remove heading hashes
    .replace(/\*\*(.+?)\*\*/g, "$1") // remove bold
    .replace(/\*(.+?)\*/g, "$1") // remove italics
    .replace(/`{3}[\s\S]*?`{3}/g, (match) => match.replace(/`{3}\w*\n?/g, "")) // clean code fences
    .replace(/`(.+?)`/g, "$1") // remove inline code ticks
    .trim();
}

/**
 * Build a structured, executive-styled PDF Document using jsPDF
 */
export function buildPdfDocument(title, content) {
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 18;
  const maxLineWidth = pageWidth - margin * 2; // ~174mm
  const cleanTitle = cleanDocumentText(title) || "Document";
  const cleanedContent = cleanDocumentText(content) || "";

  let curY = margin + 6;

  function checkPage(needHeight = 10) {
    if (curY + needHeight > pageHeight - margin - 8) {
      doc.addPage();
      curY = margin + 6;
      return true;
    }
    return false;
  }

  // Document Title
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.setTextColor(15, 23, 42); // #0F172A
  doc.text(cleanTitle, margin, curY);
  curY += 5;

  // Title underline accent (emerald #10B981)
  doc.setDrawColor(16, 185, 129);
  doc.setLineWidth(0.8);
  doc.line(margin, curY, margin + 45, curY);
  curY += 5;

  // Subtitle
  const dateStr = new Date().toLocaleDateString("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
  });
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(100, 116, 139);
  doc.text(`Executive Document • Generated by TharikAI • ${dateStr}`, margin, curY);
  curY += 10;

  const lines = cleanedContent.replace(/\r\n/g, "\n").split("\n");
  let inCode = false;
  let codeBuffer = [];
  let tableRows = [];

  function flushPdfTable() {
    if (tableRows.length === 0) return;
    const isHeaderSeparator = (row) => row.every((c) => /^[-: ]+$/.test(c));
    const validRows = tableRows.filter((r) => !isHeaderSeparator(r));
    if (validRows.length > 0) {
      const numCols = Math.max(1, ...validRows.map((r) => r.length));
      const colWidth = maxLineWidth / numCols;
      const rowHeight = 7.5;

      checkPage(rowHeight * 2);

      validRows.forEach((row, rIdx) => {
        checkPage(rowHeight);
        const isHeader = rIdx === 0;

        // Background fill
        if (isHeader) {
          doc.setFillColor(15, 23, 42);
          doc.rect(margin, curY, maxLineWidth, rowHeight, "F");
        } else if (rIdx % 2 === 1) {
          doc.setFillColor(248, 250, 252);
          doc.rect(margin, curY, maxLineWidth, rowHeight, "F");
        }

        // Borders
        doc.setDrawColor(203, 213, 225);
        doc.setLineWidth(0.2);
        doc.rect(margin, curY, maxLineWidth, rowHeight, "S");

        // Text
        doc.setFont("helvetica", isHeader ? "bold" : "normal");
        doc.setFontSize(isHeader ? 9.5 : 9);
        doc.setTextColor(isHeader ? 255 : 30, isHeader ? 255 : 41, isHeader ? 255 : 59);

        row.forEach((cellText, cIdx) => {
          if (cIdx < numCols) {
            const cellClean = cellText.replace(/[*_`]/g, "").trim();
            const maxChars = Math.max(10, Math.floor(colWidth / 2.2));
            const display = cellClean.length > maxChars ? cellClean.slice(0, maxChars - 2) + ".." : cellClean;
            doc.text(display, margin + cIdx * colWidth + 2.5, curY + 5);
          }
        });

        curY += rowHeight;
      });

      curY += 4;
    }
    tableRows = [];
  }

  for (let i = 0; i < lines.length; i++) {
    const rawLine = lines[i];
    const line = rawLine.trim();

    // Code blocks
    if (line.startsWith("```")) {
      if (inCode) {
        checkPage(codeBuffer.length * 4.5 + 8);
        const codeBoxH = codeBuffer.length * 4.5 + 6;
        doc.setFillColor(248, 250, 252);
        doc.rect(margin, curY, maxLineWidth, codeBoxH, "F");

        // Emerald left border
        doc.setDrawColor(16, 185, 129);
        doc.setLineWidth(1.0);
        doc.line(margin, curY, margin, curY + codeBoxH);

        doc.setFont("courier", "normal");
        doc.setFontSize(8.5);
        doc.setTextColor(15, 23, 42);

        let codeY = curY + 4;
        codeBuffer.forEach((cLine) => {
          doc.text(cLine.slice(0, 85) || " ", margin + 3, codeY);
          codeY += 4.5;
        });

        curY += codeBoxH + 4;
        codeBuffer = [];
        inCode = false;
      } else {
        flushPdfTable();
        inCode = true;
      }
      continue;
    }

    if (inCode) {
      codeBuffer.push(rawLine);
      continue;
    }

    // Markdown tables
    if (line.startsWith("|") && line.endsWith("|")) {
      const cells = line
        .split("|")
        .slice(1, -1)
        .map((s) => s.trim());
      tableRows.push(cells);
      continue;
    } else if (tableRows.length > 0) {
      flushPdfTable();
    }

    if (!line) continue;

    // Horizontal Rule
    if (/^[-*_]{3,}$/.test(line)) {
      checkPage(6);
      doc.setDrawColor(226, 232, 240);
      doc.setLineWidth(0.4);
      doc.line(margin, curY + 2, margin + maxLineWidth, curY + 2);
      curY += 6;
      continue;
    }

    // Headings
    if (line.startsWith("# ")) {
      const headingText = line.slice(2).trim().replace(/\*\*/g, "");
      if (headingText.toLowerCase() === cleanTitle.toLowerCase()) continue;
      checkPage(14);
      curY += 4;
      doc.setFont("helvetica", "bold");
      doc.setFontSize(14.5);
      doc.setTextColor(15, 23, 42);
      doc.text(headingText, margin, curY);
      curY += 6.5;
    } else if (line.startsWith("## ")) {
      const headingText = line.slice(3).trim().replace(/\*\*/g, "");
      checkPage(12);
      curY += 3.5;
      doc.setFont("helvetica", "bold");
      doc.setFontSize(12.5);
      doc.setTextColor(30, 41, 59);
      doc.text(headingText, margin, curY);
      curY += 5.5;
    } else if (line.startsWith("### ")) {
      const headingText = line.slice(4).trim().replace(/\*\*/g, "");
      checkPage(10);
      curY += 2.5;
      doc.setFont("helvetica", "bold");
      doc.setFontSize(11);
      doc.setTextColor(51, 65, 85);
      doc.text(headingText, margin, curY);
      curY += 5;
    } else if (/^[-*•]\s+/.test(line)) {
      const bulletText = line.replace(/^[-*•]\s+/, "").replace(/[*_`]/g, "").trim();
      checkPage(6);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(10);
      doc.setTextColor(16, 185, 129); // emerald bullet
      doc.text("•", margin + 1, curY);

      doc.setFont("helvetica", "normal");
      doc.setFontSize(9.5);
      doc.setTextColor(30, 41, 59);
      const splitBullet = doc.splitTextToSize(bulletText, maxLineWidth - 6);
      for (let bIdx = 0; bIdx < splitBullet.length; bIdx++) {
        if (bIdx > 0) checkPage(5);
        doc.text(splitBullet[bIdx], margin + 6, curY);
        curY += 5;
      }
      curY += 1;
    } else if (/^\d+\.\s+/.test(line)) {
      const numMatch = line.match(/^(\d+\.)\s+(.+)$/);
      const numPrefix = numMatch ? numMatch[1] : "";
      const numText = (numMatch ? numMatch[2] : line).replace(/[*_`]/g, "").trim();
      checkPage(6);

      doc.setFont("helvetica", "bold");
      doc.setFontSize(9.5);
      doc.setTextColor(16, 185, 129);
      doc.text(numPrefix, margin + 1, curY);

      doc.setFont("helvetica", "normal");
      doc.setFontSize(9.5);
      doc.setTextColor(30, 41, 59);
      const splitNum = doc.splitTextToSize(numText, maxLineWidth - 8);
      for (let nIdx = 0; nIdx < splitNum.length; nIdx++) {
        if (nIdx > 0) checkPage(5);
        doc.text(splitNum[nIdx], margin + 8, curY);
        curY += 5;
      }
      curY += 1;
    } else if (line.startsWith("> ")) {
      const quoteText = line.slice(2).replace(/[*_`]/g, "").trim();
      checkPage(8);
      doc.setDrawColor(16, 185, 129);
      doc.setLineWidth(0.8);
      doc.line(margin + 2, curY - 3, margin + 2, curY + 4);

      doc.setFont("helvetica", "italic");
      doc.setFontSize(9.5);
      doc.setTextColor(71, 85, 105);
      const splitQuote = doc.splitTextToSize(quoteText, maxLineWidth - 8);
      for (let qIdx = 0; qIdx < splitQuote.length; qIdx++) {
        if (qIdx > 0) checkPage(5);
        doc.text(splitQuote[qIdx], margin + 6, curY);
        curY += 5;
      }
      curY += 2;
    } else {
      const cleanPara = line.replace(/[*_`]/g, "").trim();
      doc.setFont("helvetica", "normal");
      doc.setFontSize(9.5);
      doc.setTextColor(30, 41, 59);
      const splitPara = doc.splitTextToSize(cleanPara, maxLineWidth);
      for (const pLine of splitPara) {
        checkPage(5);
        doc.text(pLine, margin, curY);
        curY += 5;
      }
      curY += 2.5;
    }
  }

  flushPdfTable();

  // Clean page numbers
  const totalPages = doc.internal.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8.5);
    doc.setTextColor(148, 163, 184);
    doc.text(
      `Page ${i} of ${totalPages}`,
      pageWidth - margin,
      pageHeight - 10,
      { align: "right" }
    );
  }

  return doc;
}

/**
 * Export message or content as a formatted PDF Document
 */
export function exportToPdf(title, content, filename = "TharikAI_Document.pdf") {
  try {
    const doc = buildPdfDocument(title, content);
    const finalName = filename.endsWith(".pdf") ? filename : `${filename}.pdf`;
    doc.save(finalName);
    return true;
  } catch (err) {
    console.error("PDF Export Error:", err);
    throw err;
  }
}

/**
 * Robustly parses markdown tables or text into 2D rows
 */
export function parseMarkdownTableData(textOrMarkdown) {
  if (Array.isArray(textOrMarkdown)) return textOrMarkdown;
  if (!textOrMarkdown || typeof textOrMarkdown !== "string") return [];

  const rawLines = textOrMarkdown.trim().split("\n");
  const rows = [];
  let foundTable = false;

  for (const line of rawLines) {
    const trimmed = line.trim();
    if (!trimmed.includes("|")) continue;
    // Skip separator divider line like |---|---| or |:---:|
    if (/^\|?\s*[-:]+[-| :]*\|?$/.test(trimmed)) {
      foundTable = true;
      continue;
    }

    let content = trimmed;
    if (content.startsWith("|")) content = content.slice(1);
    if (content.endsWith("|")) content = content.slice(0, -1);

    const cols = content
      .split("|")
      .map((c) => cleanDocumentText(c.trim()).replace(/[*_`]/g, "").trim());

    if (cols.length > 0 && cols.some((c) => c.length > 0)) {
      rows.push(cols);
      foundTable = true;
    }
  }

  if (!foundTable || rows.length === 0) {
    const textLines = (textOrMarkdown || "").split("\n").filter((l) => l.trim());
    for (const l of textLines) {
      const cleaned = cleanDocumentText(l).replace(/[*_`#]/g, "").trim();
      if (cleaned) rows.push([cleaned]);
    }
  }

  return rows;
}

/**
 * Export tabular data or Markdown Table into Excel (.xlsx) / CSV
 */
export function exportTableToExcel(tableDataOrMarkdown, filename = "TharikAI_Data.xlsx") {
  try {
    const rows = parseMarkdownTableData(tableDataOrMarkdown);
    const ws = XLSX.utils.aoa_to_sheet(rows);

    // Auto-fit column widths so cell text is not truncated or hidden
    if (rows.length > 0 && rows[0].length > 0) {
      const colWidths = rows[0].map((_, colIdx) => {
        let maxLen = 14;
        rows.forEach((r) => {
          const val = r[colIdx] != null ? String(r[colIdx]) : "";
          if (val.length > maxLen) {
            maxLen = Math.min(val.length + 4, 50);
          }
        });
        return { wch: maxLen };
      });
      ws["!cols"] = colWidths;
    }

    const wb = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(wb, ws, "Sheet1");

    const finalName = filename.endsWith(".xlsx") ? filename : `${filename}.xlsx`;
    XLSX.writeFile(wb, finalName);
    return true;
  } catch (err) {
    console.error("Excel Export Error:", err);
    throw err;
  }
}

/**
 * Parse markdown inline formatting into docx TextRun elements
 */
function parseInlineFormatting(text, baseFont = "Segoe UI") {
  if (!text) return [];
  const runs = [];
  const regex = /(\*\*\*[\s\S]+?\*\*\*|\*\*[\s\S]+?\*\*|\*[\s\S]+?\*|___[\s\S]+?___|__[\s\S]+?__|`[\s\S]+?`|\[[\s\S]+?\]\([\s\S]+?\))/g;
  let lastIndex = 0;
  let match;

  while ((match = regex.exec(text)) !== null) {
    if (match.index > lastIndex) {
      runs.push(
        new TextRun({
          text: text.slice(lastIndex, match.index),
          font: baseFont,
          size: 22, // 11pt
          color: "1E293B",
        })
      );
    }
    const token = match[0];
    if (
      (token.startsWith("***") && token.endsWith("***")) ||
      (token.startsWith("___") && token.endsWith("___"))
    ) {
      runs.push(
        new TextRun({
          text: token.slice(3, -3),
          bold: true,
          italics: true,
          font: baseFont,
          size: 22,
          color: "0F172A",
        })
      );
    } else if (
      (token.startsWith("**") && token.endsWith("**")) ||
      (token.startsWith("__") && token.endsWith("__"))
    ) {
      runs.push(
        new TextRun({
          text: token.slice(2, -2),
          bold: true,
          font: baseFont,
          size: 22,
          color: "0F172A",
        })
      );
    } else if (token.startsWith("*") && token.endsWith("*")) {
      runs.push(
        new TextRun({
          text: token.slice(1, -1),
          italics: true,
          font: baseFont,
          size: 22,
          color: "334155",
        })
      );
    } else if (token.startsWith("`") && token.endsWith("`")) {
      runs.push(
        new TextRun({
          text: token.slice(1, -1),
          font: "Consolas",
          size: 20, // 10pt
          color: "0F172A",
          shading: { fill: "F1F5F9", type: ShadingType.CLEAR },
        })
      );
    } else if (token.startsWith("[") && token.includes("](")) {
      const linkMatch = token.match(/^\[([\s\S]*?)\]\(([\s\S]*?)\)$/);
      const label = linkMatch ? linkMatch[1] : token;
      runs.push(
        new TextRun({
          text: label,
          font: baseFont,
          size: 22,
          color: "0284C7",
          underline: {},
        })
      );
    }
    lastIndex = regex.lastIndex;
  }

  if (lastIndex < text.length) {
    runs.push(
      new TextRun({
        text: text.slice(lastIndex),
        font: baseFont,
        size: 22,
        color: "1E293B",
      })
    );
  }

  return runs.length > 0
    ? runs
    : [new TextRun({ text, font: baseFont, size: 22, color: "1E293B" })];
}

/**
 * Generate a genuine Microsoft Word (.docx) OpenXML binary Blob from markdown
 */
export async function generateWordDocxBlob(title, content) {
  const cleanTitle = cleanDocumentText(title) || "Document";
  const cleanedContent = cleanDocumentText(content) || "No content provided.";

  const children = [];

  // Document Title
  children.push(
    new Paragraph({
      children: [
        new TextRun({
          text: cleanTitle,
          bold: true,
          font: "Segoe UI",
          size: 36, // 18pt
          color: "0F172A",
        }),
      ],
      spacing: { before: 120, after: 80 },
    })
  );

  // Subtitle / Brand header bar
  const dateStr = new Date().toLocaleDateString("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
  });
  children.push(
    new Paragraph({
      children: [
        new TextRun({
          text: `Executive Document • Generated by TharikAI • ${dateStr}`,
          font: "Segoe UI",
          size: 18, // 9pt
          color: "64748B",
        }),
      ],
      border: {
        bottom: { style: BorderStyle.SINGLE, size: 8, color: "10B981" },
      },
      spacing: { before: 0, after: 320 },
    })
  );

  const lines = cleanedContent.replace(/\r\n/g, "\n").split("\n");
  let inCode = false;
  let codeBuffer = [];
  let tableRows = [];

  function flushTable() {
    if (tableRows.length === 0) return;
    const docxRows = [];
    const isHeaderSeparator = (row) => row.every((c) => /^[-: ]+$/.test(c));

    let isHeader = true;
    for (let rIdx = 0; rIdx < tableRows.length; rIdx++) {
      const r = tableRows[rIdx];
      if (isHeaderSeparator(r)) {
        isHeader = false;
        continue;
      }
      const isHeaderRow = isHeader;
      const isAltRow = !isHeaderRow && rIdx % 2 === 1;

      const cells = r.map((c) => {
        return new TableCell({
          children: [
            new Paragraph({
              children: isHeaderRow
                ? [
                    new TextRun({
                      text: c,
                      bold: true,
                      color: "FFFFFF",
                      font: "Segoe UI",
                      size: 20, // 10pt
                    }),
                  ]
                : parseInlineFormatting(c),
              spacing: { before: 80, after: 80 },
            }),
          ],
          shading: isHeaderRow
            ? { fill: "0F172A", type: ShadingType.CLEAR }
            : isAltRow
            ? { fill: "F8FAFC", type: ShadingType.CLEAR }
            : undefined,
          borders: {
            top: { style: BorderStyle.SINGLE, size: 4, color: "CBD5E1" },
            bottom: { style: BorderStyle.SINGLE, size: 4, color: "CBD5E1" },
            left: { style: BorderStyle.SINGLE, size: 4, color: "CBD5E1" },
            right: { style: BorderStyle.SINGLE, size: 4, color: "CBD5E1" },
          },
          margins: {
            top: 100,
            bottom: 100,
            left: 140,
            right: 140,
          },
        });
      });

      docxRows.push(new TableRow({ children: cells }));
      isHeader = false;
    }

    if (docxRows.length > 0) {
      children.push(
        new Table({
          width: { size: 100, type: WidthType.PERCENTAGE },
          rows: docxRows,
        })
      );
      children.push(new Paragraph({ text: "", spacing: { after: 140 } }));
    }
    tableRows = [];
  }

  for (let i = 0; i < lines.length; i++) {
    const rawLine = lines[i];
    const line = rawLine.trim();

    // Code blocks
    if (line.startsWith("```")) {
      if (inCode) {
        children.push(
          new Table({
            width: { size: 100, type: WidthType.PERCENTAGE },
            rows: [
              new TableRow({
                children: [
                  new TableCell({
                    shading: { fill: "F8FAFC", type: ShadingType.CLEAR },
                    borders: {
                      top: { style: BorderStyle.SINGLE, size: 4, color: "E2E8F0" },
                      bottom: { style: BorderStyle.SINGLE, size: 4, color: "E2E8F0" },
                      left: { style: BorderStyle.SINGLE, size: 16, color: "10B981" },
                      right: { style: BorderStyle.SINGLE, size: 4, color: "E2E8F0" },
                    },
                    margins: { top: 120, bottom: 120, left: 160, right: 160 },
                    children: codeBuffer.map(
                      (cLine) =>
                        new Paragraph({
                          children: [
                            new TextRun({
                              text: cLine || " ",
                              font: "Consolas",
                              size: 19,
                              color: "0F172A",
                            }),
                          ],
                          spacing: { before: 20, after: 20 },
                        })
                    ),
                  }),
                ],
              }),
            ],
          })
        );
        children.push(new Paragraph({ text: "", spacing: { after: 140 } }));
        codeBuffer = [];
        inCode = false;
      } else {
        flushTable();
        inCode = true;
      }
      continue;
    }

    if (inCode) {
      codeBuffer.push(rawLine);
      continue;
    }

    // Markdown tables
    if (line.startsWith("|") && line.endsWith("|")) {
      const cells = line
        .split("|")
        .slice(1, -1)
        .map((s) => s.trim());
      tableRows.push(cells);
      continue;
    } else if (tableRows.length > 0) {
      flushTable();
    }

    if (!line) {
      continue;
    }

    // Horizontal Rule
    if (/^[-*_]{3,}$/.test(line)) {
      children.push(
        new Paragraph({
          border: {
            bottom: { style: BorderStyle.SINGLE, size: 6, color: "E2E8F0" },
          },
          spacing: { before: 140, after: 140 },
        })
      );
      continue;
    }

    // Headings
    if (line.startsWith("# ")) {
      const headingText = line.slice(2).trim();
      // If heading equals the document title, skip duplicating the title
      if (headingText.toLowerCase() === cleanTitle.toLowerCase()) {
        continue;
      }
      children.push(
        new Paragraph({
          children: parseInlineFormatting(headingText),
          heading: HeadingLevel.HEADING_1,
          border: {
            bottom: { style: BorderStyle.SINGLE, size: 4, color: "10B981" },
          },
          spacing: { before: 280, after: 120 },
        })
      );
    } else if (line.startsWith("## ")) {
      children.push(
        new Paragraph({
          children: parseInlineFormatting(line.slice(3).trim()),
          heading: HeadingLevel.HEADING_2,
          spacing: { before: 240, after: 100 },
        })
      );
    } else if (line.startsWith("### ")) {
      children.push(
        new Paragraph({
          children: parseInlineFormatting(line.slice(4).trim()),
          heading: HeadingLevel.HEADING_3,
          spacing: { before: 200, after: 80 },
        })
      );
    } else if (line.startsWith("#### ")) {
      children.push(
        new Paragraph({
          children: parseInlineFormatting(line.slice(5).trim()),
          heading: HeadingLevel.HEADING_4,
          spacing: { before: 160, after: 60 },
        })
      );
    } else if (/^[-*•]\s+/.test(line)) {
      const bulletText = line.replace(/^[-*•]\s+/, "").trim();
      children.push(
        new Paragraph({
          bullet: { level: 0 },
          children: parseInlineFormatting(bulletText),
          spacing: { before: 40, after: 40, line: 276 },
        })
      );
    } else if (/^\d+\.\s+/.test(line)) {
      const numMatch = line.match(/^(\d+\.)\s+(.+)$/);
      children.push(
        new Paragraph({
          children: [
            new TextRun({
              text: `${numMatch[1]}  `,
              bold: true,
              font: "Segoe UI",
              size: 22,
              color: "10B981",
            }),
            ...parseInlineFormatting(numMatch[2]),
          ],
          spacing: { before: 40, after: 40, line: 276 },
        })
      );
    } else if (line.startsWith("> ")) {
      children.push(
        new Paragraph({
          children: parseInlineFormatting(line.slice(2).trim()),
          indent: { left: 400 },
          border: {
            left: { style: BorderStyle.SINGLE, size: 12, color: "10B981" },
          },
          spacing: { before: 100, after: 100, line: 276 },
        })
      );
    } else {
      children.push(
        new Paragraph({
          children: parseInlineFormatting(line),
          spacing: { before: 60, after: 120, line: 276 },
        })
      );
    }
  }

  flushTable();

  const doc = new Document({
    sections: [
      {
        properties: {
          page: {
            margin: {
              top: 1440,
              bottom: 1440,
              left: 1440,
              right: 1440,
            },
          },
        },
        footers: {
          default: new Footer({
            children: [
              new Paragraph({
                alignment: AlignmentType.RIGHT,
                children: [
                  new TextRun({
                    text: "Page ",
                    font: "Segoe UI",
                    size: 18,
                    color: "94A3B8",
                  }),
                  new TextRun({
                    children: [PageNumber.CURRENT],
                    font: "Segoe UI",
                    size: 18,
                    color: "94A3B8",
                  }),
                  new TextRun({
                    text: " of ",
                    font: "Segoe UI",
                    size: 18,
                    color: "94A3B8",
                  }),
                  new TextRun({
                    children: [PageNumber.TOTAL_PAGES],
                    font: "Segoe UI",
                    size: 18,
                    color: "94A3B8",
                  }),
                ],
              }),
            ],
          }),
        },
        children,
      },
    ],
  });

  return await Packer.toBlob(doc);
}

/**
 * Export content to formatted Microsoft Word (.docx)
 */
export async function exportToWordDoc(title, content, filename = "Document.docx") {
  try {
    const blob = await generateWordDocxBlob(title, content);
    const finalName = filename.endsWith(".docx")
      ? filename
      : filename.endsWith(".doc")
      ? `${filename.slice(0, -4)}.docx`
      : `${filename}.docx`;
    triggerDownload(blob, finalName);
    return true;
  } catch (err) {
    console.error("Word Export Error:", err);
    throw err;
  }
}

/**
 * Export all formats (Word .docx, Excel .xlsx, PPT .pptx, PDF .pdf) packaged into a single ZIP
 */
/**
 * Build a structured, auto-fitted PowerPoint presentation using PptxGenJS
 */
export function buildPptxPresentation(title, content) {
  const pptx = new pptxgen();
  pptx.layout = "LAYOUT_16x9"; // 10.0" wide by 5.625" high in PptxGenJS
  const cleanTitle = cleanDocumentText(title) || "Presentation";
  pptx.title = cleanTitle;

  // 1. Title Slide (Slide 1)
  const titleSlide = pptx.addSlide();
  titleSlide.background = { color: "0F172A" }; // Executive dark slate theme

  // Decorative accent line
  titleSlide.addShape(pptx.ShapeType.rect, {
    x: 0.8,
    y: 1.8,
    w: 0.08,
    h: 1.8,
    fill: { color: "F97316" }, // Orange accent
  });

  titleSlide.addText(cleanTitle, {
    x: 1.1,
    y: 1.8,
    w: 8.0,
    h: 1.2,
    fontSize: 28,
    bold: true,
    color: "FFFFFF",
    valign: "middle",
    wrap: true,
  });

  const dateStr = new Date().toLocaleDateString("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
  });
  titleSlide.addText(`Executive Presentation • Generated by TharikAI • ${dateStr}`, {
    x: 1.1,
    y: 3.1,
    w: 8.0,
    h: 0.5,
    fontSize: 13,
    color: "94A3B8",
  });

  // 2. Parse sections
  const rawClean = cleanDocumentText(content);
  const lines = rawClean.split("\n");
  const sections = [];
  let curSection = { title: "", bullets: [], tableRows: [] };

  function flushSection() {
    if (curSection.title || curSection.bullets.length > 0 || curSection.tableRows.length > 0) {
      sections.push({ ...curSection });
      curSection = { title: "", bullets: [], tableRows: [] };
    }
  }

  for (const rawLine of lines) {
    const line = rawLine.trim();
    if (!line) continue;

    // Header match
    if (line.startsWith("# ") || line.startsWith("## ") || line.startsWith("### ") || line.match(/^Slide\s+\d+:/i)) {
      flushSection();
      curSection.title = line
        .replace(/^#+\s*/, "")
        .replace(/^Slide\s+\d+:\s*/i, "")
        .replace(/\*\*/g, "")
        .trim();
      continue;
    }

    // Markdown Table row match
    if (line.startsWith("|") && line.endsWith("|")) {
      if (/^\|?\s*[-:]+[-| :]*\|?$/.test(line)) continue; // skip divider
      const cells = line
        .split("|")
        .slice(1, -1)
        .map((c) => c.replace(/[*_`]/g, "").trim());
      if (cells.length > 0 && cells.some((c) => c.length > 0)) {
        curSection.tableRows.push(cells);
      }
      continue;
    }

    // Bullet / text match
    const cleanBullet = line
      .replace(/^[-*•]\s*/, "")
      .replace(/^\d+\.\s*/, "")
      .replace(/\*\*/g, "")
      .trim();
    if (cleanBullet.length > 0) {
      curSection.bullets.push(cleanBullet);
    }
  }
  flushSection();

  if (sections.length === 0) {
    sections.push({
      title: cleanTitle,
      bullets: lines.slice(0, 5).map((x) => cleanDocumentText(x.trim())).filter(Boolean),
      tableRows: [],
    });
  }

  // 3. Process sections into fitted slides
  const finalSlides = [];
  sections.forEach((sec) => {
    // If section contains a table:
    if (sec.tableRows.length > 0) {
      const maxTableRows = 6;
      const headerRow = sec.tableRows[0];
      const dataRows = sec.tableRows.slice(1);

      if (dataRows.length <= maxTableRows) {
        finalSlides.push({
          title: sec.title || "Data & Analysis",
          type: "table",
          rows: sec.tableRows,
        });
      } else {
        for (let i = 0; i < dataRows.length; i += maxTableRows) {
          const chunk = dataRows.slice(i, i + maxTableRows);
          const part = i === 0 ? "" : ` (Cont. ${Math.floor(i / maxTableRows) + 1})`;
          finalSlides.push({
            title: `${sec.title || "Data Table"}${part}`,
            type: "table",
            rows: [headerRow, ...chunk],
          });
        }
      }
    }

    // If section contains bullets:
    if (sec.bullets.length > 0) {
      const maxBulletsPerSlide = 5;
      for (let i = 0; i < sec.bullets.length; i += maxBulletsPerSlide) {
        const chunk = sec.bullets.slice(i, i + maxBulletsPerSlide);
        const part = i === 0 ? "" : ` (Cont. ${Math.floor(i / maxBulletsPerSlide) + 1})`;
        finalSlides.push({
          title: `${sec.title || "Overview"}${part}`,
          type: "bullets",
          bullets: chunk,
        });
      }
    }
  });

  // 4. Render slides
  finalSlides.forEach((sd, sIdx) => {
    const slide = pptx.addSlide();
    slide.background = { color: "F8FAFC" };

    // Header banner: 10" wide by 0.9" high
    slide.addShape(pptx.ShapeType.rect, {
      x: 0,
      y: 0,
      w: "100%",
      h: 0.9,
      fill: { color: "0F172A" },
    });

    // Title: x=0.6, y=0.15, w=8.8, h=0.6
    slide.addText(sd.title, {
      x: 0.6,
      y: 0.15,
      w: 8.8,
      h: 0.6,
      fontSize: 18,
      bold: true,
      color: "FFFFFF",
      valign: "middle",
      wrap: true,
    });

    // White card container in slide body: x=0.6, y=1.15, w=8.8, h=3.85
    slide.addShape(pptx.ShapeType.rect, {
      x: 0.6,
      y: 1.15,
      w: 8.8,
      h: 3.85,
      fill: { color: "FFFFFF" },
      line: { color: "E2E8F0", width: 1 },
    });

    if (sd.type === "table" && sd.rows && sd.rows.length > 0) {
      const formattedTable = sd.rows.map((row, rIdx) => {
        const isHeader = rIdx === 0;
        return row.map((cellText) => ({
          text: cellText,
          options: {
            fill: { color: isHeader ? "0F172A" : rIdx % 2 === 1 ? "F8FAFC" : "FFFFFF" },
            color: isHeader ? "FFFFFF" : "1E293B",
            bold: isHeader,
            fontSize: isHeader ? 11 : 10,
            valign: "middle",
            align: isHeader ? "center" : "left",
            margin: [6, 8, 6, 8],
          },
        }));
      });

      slide.addTable(formattedTable, {
        x: 0.85,
        y: 1.35,
        w: 8.3,
        border: { pt: 1, color: "CBD5E1" },
        autoPage: false,
      });
    } else if (sd.bullets && sd.bullets.length > 0) {
      // Dynamic auto-fitting font size based on text volume
      const totalLen = sd.bullets.reduce((acc, b) => acc + b.length, 0);
      let fontSize = 12.5;
      let spacingAfter = 12;

      if (sd.bullets.length <= 3 && totalLen < 250) {
        fontSize = 14;
        spacingAfter = 16;
      } else if (sd.bullets.length >= 5 || totalLen > 400) {
        fontSize = 11;
        spacingAfter = 8;
      }

      const textItems = sd.bullets.map((b) => ({
        text: b,
        options: {
          fontSize: fontSize,
          color: "1E293B",
          bullet: { type: "bullet", code: "2022" },
          breakLine: true,
          spacing: { after: spacingAfter },
        },
      }));

      slide.addText(textItems, {
        x: 0.85,
        y: 1.35,
        w: 8.3,
        h: 3.45,
        margin: 0,
        valign: "top",
        wrap: true,
      });
    }

    // Footer
    slide.addText(cleanTitle, {
      x: 0.6,
      y: 5.15,
      w: 5.0,
      h: 0.35,
      fontSize: 9,
      color: "94A3B8",
    });

    slide.addText(`Slide ${sIdx + 2} of ${finalSlides.length + 1}`, {
      x: 5.6,
      y: 5.15,
      w: 3.8,
      h: 0.35,
      fontSize: 9,
      color: "94A3B8",
      align: "right",
    });
  });

  return pptx;
}

/**
 * Export content to a PowerPoint Presentation (.pptx)
 */
export async function exportToPptx(title, content, filename = "Presentation.pptx") {
  try {
    const cleanTitle = cleanDocumentText(title) || "Presentation";
    const pptx = buildPptxPresentation(cleanTitle, content);
    const finalName = filename.endsWith(".pptx") ? filename : `${filename}.pptx`;
    await pptx.writeFile({ fileName: finalName });
    return true;
  } catch (err) {
    console.error("PPTX Export Error:", err);
    throw err;
  }
}

/**
 * Export all formats (Word .docx, Excel .xlsx, PPT .pptx, PDF .pdf) packaged into a single ZIP
 */
export async function exportAllInOneZip(title, content, filename = "Documents_All_Formats.zip") {
  try {
    const zip = new JSZip();
    const cleanTitle = cleanDocumentText(title) || "Document";
    const base = cleanTitle.replace(/[^a-zA-Z0-9_-]/g, "_").slice(0, 32) || "Document";

    // 1. Word (.docx) - Genuine OpenXML DOCX
    try {
      const docxBlob = await generateWordDocxBlob(title, content);
      zip.file(`${base}.docx`, docxBlob);
    } catch (e) {
      console.warn("Word in zip error:", e);
    }

    // 2. Excel (.xlsx) - Auto-fitted and aligned columns
    try {
      const rows = parseMarkdownTableData(content);
      const ws = XLSX.utils.aoa_to_sheet(rows);
      if (rows.length > 0 && rows[0].length > 0) {
        ws["!cols"] = rows[0].map((_, colIdx) => {
          let maxLen = 14;
          rows.forEach((r) => {
            const val = r[colIdx] != null ? String(r[colIdx]) : "";
            if (val.length > maxLen) maxLen = Math.min(val.length + 4, 50);
          });
          return { wch: maxLen };
        });
      }
      const wb = XLSX.utils.book_new();
      XLSX.utils.book_append_sheet(wb, ws, "Sheet1");
      const excelBlob = XLSX.write(wb, { bookType: "xlsx", type: "array" });
      zip.file(`${base}.xlsx`, excelBlob);
    } catch (e) {
      console.warn("Excel in zip error:", e);
    }

    // 3. PowerPoint (.pptx) - Native 16:9 widescreen presentation with tables & auto-fitting
    try {
      const pptx = buildPptxPresentation(cleanTitle, content);
      const pptxBlob = await pptx.write({ outputType: "blob" });
      zip.file(`${base}.pptx`, pptxBlob);
    } catch (e) {
      console.warn("PPT in zip error:", e);
    }

    // 4. PDF (.pdf) - Executive structured document layout
    try {
      const doc = buildPdfDocument(cleanTitle, content);
      const pdfBlob = doc.output("blob");
      zip.file(`${base}.pdf`, pdfBlob);
    } catch (e) {
      console.warn("PDF in zip error:", e);
    }

    const blob = await zip.generateAsync({ type: "blob" });
    const finalName = filename.endsWith(".zip") ? filename : `${filename}.zip`;
    triggerDownload(blob, finalName);
    return true;
  } catch (err) {
    console.error("ZIP All Error:", err);
    throw err;
  }
}

/**
 * Export files or multi-file code into a single .ZIP archive
 */
export async function exportToZip(files, zipFilename = "Project_Archive.zip") {
  try {
    const zip = new JSZip();

    files.forEach((file) => {
      zip.file(file.name, file.content);
    });

    const blob = await zip.generateAsync({ type: "blob" });
    const finalName = zipFilename.endsWith(".zip") ? zipFilename : `${zipFilename}.zip`;
    triggerDownload(blob, finalName);
    return true;
  } catch (err) {
    console.error("ZIP Export Error:", err);
    throw err;
  }
}

/**
 * Extract all code blocks from markdown content
 * Returns array of { language, name, content }
 */
export function extractCodeBlocksFromMarkdown(markdownText) {
  const codeBlockRegex = /```([a-zA-Z0-9_-]*)\n([\s\S]*?)```/g;
  const blocks = [];
  let match;
  let index = 1;

  const extMap = {
    python: "py",
    py: "py",
    javascript: "js",
    js: "js",
    jsx: "jsx",
    typescript: "ts",
    ts: "ts",
    tsx: "tsx",
    html: "html",
    css: "css",
    json: "json",
    sql: "sql",
    cpp: "cpp",
    c: "c",
    java: "java",
    go: "go",
    rust: "rs",
    rs: "rs",
    php: "php",
    ruby: "rb",
    sh: "sh",
    bash: "sh",
    markdown: "md",
    md: "md",
  };

  while ((match = codeBlockRegex.exec(markdownText)) !== null) {
    const lang = (match[1] || "txt").toLowerCase();
    const code = match[2];
    const ext = extMap[lang] || lang || "txt";
    blocks.push({
      language: lang,
      extension: ext,
      name: `code_${index}.${ext}`,
      content: code,
    });
    index++;
  }

  return blocks;
}

/**
 * Export tabular data or Markdown Table into CSV (.csv)
 */
export function exportTableToCsv(tableDataOrMarkdown, filename = "TharikAI_Data.csv") {
  try {
    const rows = parseMarkdownTableData(tableDataOrMarkdown);
    const ws = XLSX.utils.aoa_to_sheet(rows);
    const csv = XLSX.utils.sheet_to_csv(ws);
    const finalName = filename.endsWith(".csv") ? filename : `${filename}.csv`;
    downloadTextFile(finalName, csv, "text/csv;charset=utf-8;");
    return true;
  } catch (err) {
    console.error("CSV Export Error:", err);
    throw err;
  }
}


