import { jsPDF } from "jspdf";
import * as XLSX from "xlsx";
import JSZip from "jszip";
import pptxgen from "pptxgenjs";

/**
 * Standard trigger to download blob in browser
 */
export function triggerDownload(blob, filename) {
  const url = window.URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => window.URL.revokeObjectURL(url), 1000);
}

/**
 * Download raw text or code file (e.g. script.py, index.html, styles.css)
 */
export function downloadTextFile(filename, content, mimeType = "text/plain;charset=utf-8") {
  const blob = new Blob([content], { type: mimeType });
  triggerDownload(blob, filename);
}

/**
 * Clean markdown symbols for clean document text export
 */
export function cleanMarkdownForDoc(text) {
  if (!text) return "";
  return text
    .replace(/^#+\s+/gm, "") // remove heading hashes
    .replace(/\*\*(.+?)\*\*/g, "$1") // remove bold
    .replace(/\*(.+?)\*/g, "$1") // remove italics
    .replace(/`{3}[\s\S]*?`{3}/g, (match) => match.replace(/`{3}\w*\n?/g, "")) // clean code fences
    .replace(/`(.+?)`/g, "$1") // remove inline code ticks
    .replace(/\[(.+?)\]\((.+?)\)/g, "$1 ($2)") // links
    .replace(/!\[(.*?)\]\((.*?)\)/g, "") // remove markdown images
    .trim();
}

/**
 * Export message or content as a PDF Document
 */
export function exportToPdf(title, content, filename = "TharikAI_Document.pdf") {
  try {
    const doc = new jsPDF({
      orientation: "portrait",
      unit: "mm",
      format: "a4",
    });

    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 16;
    const maxLineWidth = pageWidth - margin * 2;

    // Header bar
    doc.setFillColor(16, 185, 129); // Emerald primary accent
    doc.rect(0, 0, pageWidth, 12, "F");

    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(255, 255, 255);
    doc.text("TharikAI Assistant", margin, 8);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.text(new Date().toLocaleDateString(), pageWidth - margin - 20, 8);

    // Title
    doc.setFont("helvetica", "bold");
    doc.setFontSize(16);
    doc.setTextColor(30, 41, 59);
    doc.text(title || "Generated Document", margin, 24);

    // Content Body
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10.5);
    doc.setTextColor(51, 65, 85);

    const cleanContent = cleanMarkdownForDoc(content);
    const lines = doc.splitTextToSize(cleanContent, maxLineWidth);

    let cursorY = 32;
    const lineHeight = 6;

    for (let i = 0; i < lines.length; i++) {
      if (cursorY + lineHeight > pageHeight - margin) {
        doc.addPage();
        cursorY = margin + 5;
      }
      doc.text(lines[i], margin, cursorY);
      cursorY += lineHeight;
    }

    // Footer
    const totalPages = doc.internal.getNumberOfPages();
    for (let i = 1; i <= totalPages; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.setTextColor(148, 163, 184);
      doc.text(
        `Generated by TharikAI • Page ${i} of ${totalPages}`,
        pageWidth / 2,
        pageHeight - 8,
        { align: "center" }
      );
    }

    doc.save(filename.endsWith(".pdf") ? filename : `${filename}.pdf`);
    return true;
  } catch (err) {
    console.error("PDF Export Error:", err);
    throw err;
  }
}

/**
 * Export tabular data or Markdown Table into Excel (.xlsx) / CSV
 */
export function exportTableToExcel(tableDataOrMarkdown, filename = "TharikAI_Data.xlsx") {
  try {
    let rows = [];

    if (Array.isArray(tableDataOrMarkdown)) {
      rows = tableDataOrMarkdown;
    } else if (typeof tableDataOrMarkdown === "string") {
      // Parse markdown table format: | Col 1 | Col 2 |
      const rawLines = tableDataOrMarkdown.trim().split("\n");
      for (const line of rawLines) {
        if (!line.includes("|")) continue;
        if (line.match(/^\|?\s*[-:]+[-| :]*\|?$/)) continue; // skip divider line
        const cols = line
          .split("|")
          .map((c) => c.trim())
          .filter((_, idx, arr) => (idx > 0 && idx < arr.length - 1) || arr.length <= 2);
        if (cols.length > 0) {
          rows.push(cols);
        }
      }
    }

    if (rows.length === 0) {
      // If not a formal table, split content into rows
      const textLines = (tableDataOrMarkdown || "").split("\n").filter((l) => l.trim());
      rows = textLines.map((l) => [l]);
    }

    const ws = XLSX.utils.aoa_to_sheet(rows);
    const wb = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(wb, ws, "Sheet1");

    const finalName = filename.endsWith(".xlsx") ? filename : `${filename}.xlsx`;
    XLSX.writeFile(wb, finalName);
    return true;
  } catch (err) {
    console.error("Excel Export Error:", err);
    throw err;
  }
}

/**
 * Export content to formatted Microsoft Word (.doc / .docx)
 */
export function exportToWordDoc(title, content, filename = "TharikAI_Document.doc") {
  try {
    const cleanBody = content
      .replace(/\n\n/g, "</p><p>")
      .replace(/\n/g, "<br/>")
      .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
      .replace(/\*(.+?)\*/g, "<em>$1</em>");

    const htmlContent = `
      <html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/TR/REC-html40'>
      <head>
        <meta charset='utf-8'>
        <title>${title || "TharikAI Document"}</title>
        <style>
          body { font-family: 'Segoe UI', Arial, sans-serif; font-size: 11pt; line-height: 1.6; color: #1e293b; padding: 20px; }
          h1 { color: #0f172a; font-size: 18pt; border-bottom: 2px solid #10b981; padding-bottom: 6px; }
          p { margin-bottom: 12px; }
          .footer { font-size: 9pt; color: #64748b; margin-top: 30px; border-top: 1px solid #e2e8f0; padding-top: 8px; }
        </style>
      </head>
      <body>
        <h1>${title || "TharikAI Document"}</h1>
        <p>${cleanBody}</p>
        <div class="footer">Generated by TharikAI Assistant on ${new Date().toLocaleString()}</div>
      </body>
      </html>
    `;

    const blob = new Blob(["\ufeff" + htmlContent], {
      type: "application/msword;charset=utf-8",
    });
    const finalName = filename.endsWith(".doc") ? filename : `${filename}.doc`;
    triggerDownload(blob, finalName);
    return true;
  } catch (err) {
    console.error("Word Export Error:", err);
    throw err;
  }
}

/**
 * Export files or multi-file code into a single .ZIP archive
 * files: [{ name: "index.html", content: "..." }, { name: "style.css", content: "..." }]
 */
export async function exportToZip(files, zipFilename = "TharikAI_Project.zip") {
  try {
    const zip = new JSZip();

    files.forEach((file) => {
      zip.file(file.name, file.content);
    });

    const blob = await zip.generateAsync({ type: "blob" });
    const finalName = zipFilename.endsWith(".zip") ? zipFilename : `${zipFilename}.zip`;
    triggerDownload(blob, finalName);
    return true;
  } catch (err) {
    console.error("ZIP Export Error:", err);
    throw err;
  }
}

/**
 * Extract all code blocks from markdown content
 * Returns array of { language, name, content }
 */
export function extractCodeBlocksFromMarkdown(markdownText) {
  const codeBlockRegex = /```([a-zA-Z0-9_-]*)\n([\s\S]*?)```/g;
  const blocks = [];
  let match;
  let index = 1;

  const extMap = {
    python: "py",
    py: "py",
    javascript: "js",
    js: "js",
    jsx: "jsx",
    typescript: "ts",
    ts: "ts",
    tsx: "tsx",
    html: "html",
    css: "css",
    json: "json",
    sql: "sql",
    cpp: "cpp",
    c: "c",
    java: "java",
    go: "go",
    rust: "rs",
    rs: "rs",
    php: "php",
    ruby: "rb",
    sh: "sh",
    bash: "sh",
    markdown: "md",
    md: "md",
  };

  while ((match = codeBlockRegex.exec(markdownText)) !== null) {
    const lang = (match[1] || "txt").toLowerCase();
    const code = match[2];
    const ext = extMap[lang] || lang || "txt";
    blocks.push({
      language: lang,
      extension: ext,
      name: `code_${index}.${ext}`,
      content: code,
    });
    index++;
  }

  return blocks;
}

/**
 * Export content to a PowerPoint Presentation (.pptx)
 */
export async function exportToPptx(title, content, filename = "TharikAI_Presentation.pptx") {
  try {
    const pptx = new pptxgen();
    pptx.layout = "LAYOUT_16x9";
    pptx.author = "TharikAI Assistant";
    pptx.company = "TharikAI";
    pptx.title = title || "Presentation";

    // Title Slide
    const titleSlide = pptx.addSlide();
    titleSlide.background = { color: "0F172A" }; // Deep dark background
    titleSlide.addText(title || "TharikAI Generated Presentation", {
      x: 1.0,
      y: 2.2,
      w: 11.3,
      h: 1.5,
      fontSize: 34,
      bold: true,
      color: "FFFFFF",
      align: "left",
    });
    titleSlide.addText("Generated with TharikAI Assistant", {
      x: 1.0,
      y: 3.8,
      w: 11.3,
      h: 0.8,
      fontSize: 18,
      color: "10B981", // Emerald accent
      align: "left",
    });

    // Parse sections/slides from content based on Markdown headers # or ## or paragraphs
    const lines = (content || "").split("\n");
    let currentSlideTitle = "";
    let currentSlideBullets = [];
    const slidesData = [];

    for (const rawLine of lines) {
      const line = rawLine.trim();
      if (!line) continue;

      if (line.startsWith("# ") || line.startsWith("## ") || line.startsWith("### ") || line.match(/^Slide\s+\d+:/i)) {
        if (currentSlideTitle || currentSlideBullets.length > 0) {
          slidesData.push({
            title: currentSlideTitle || "Overview",
            bullets: [...currentSlideBullets],
          });
          currentSlideBullets = [];
        }
        currentSlideTitle = line.replace(/^#+\s*/, "").replace(/^Slide\s+\d+:\s*/i, "").replace(/\*\*/g, "");
      } else {
        const cleanBullet = line.replace(/^[-*•]\s*/, "").replace(/\*\*/g, "").trim();
        if (cleanBullet.length > 0) {
          currentSlideBullets.push(cleanBullet);
        }
      }
    }

    if (currentSlideTitle || currentSlideBullets.length > 0) {
      slidesData.push({
        title: currentSlideTitle || "Summary",
        bullets: [...currentSlideBullets],
      });
    }

    // If no distinct headings were parsed, chunk content into slides of 4-5 bullet points
    if (slidesData.length === 0) {
      const cleanContent = cleanMarkdownForDoc(content);
      const paragraphs = cleanContent.split("\n\n").filter((p) => p.trim());
      slidesData.push({
        title: title || "Key Points",
        bullets: paragraphs.slice(0, 5),
      });
    }

    // Generate each content slide
    slidesData.forEach((sd) => {
      const slide = pptx.addSlide();
      slide.background = { color: "F8FAFC" };

      // Slide header banner
      slide.addShape(pptx.ShapeType.rect, {
        x: 0,
        y: 0,
        w: "100%",
        h: 1.1,
        fill: { color: "0F172A" },
      });

      slide.addText(sd.title, {
        x: 0.8,
        y: 0.25,
        w: 11.5,
        h: 0.6,
        fontSize: 22,
        bold: true,
        color: "FFFFFF",
      });

      // Bullets / content body
      const textItems = sd.bullets.slice(0, 7).map((b) => ({
        text: b,
        options: { fontSize: 15, color: "334155", bullet: true, breakLine: true, spacing: { after: 12 } },
      }));

      if (textItems.length > 0) {
        slide.addText(textItems, {
          x: 0.8,
          y: 1.5,
          w: 11.5,
          h: 5.2,
          margin: 0,
          valign: "top",
        });
      }

      // Footer
      slide.addText("TharikAI Assistant", {
        x: 0.8,
        y: 6.9,
        w: 6.0,
        h: 0.4,
        fontSize: 10,
        color: "94A3B8",
      });
    });

    const finalName = filename.endsWith(".pptx") ? filename : `${filename}.pptx`;
    await pptx.writeFile({ fileName: finalName });
    return true;
  } catch (err) {
    console.error("PPTX Export Error:", err);
    throw err;
  }
}

/**
 * Export tabular data or Markdown Table into CSV (.csv)
 */
export function exportTableToCsv(tableDataOrMarkdown, filename = "TharikAI_Data.csv") {
  try {
    let rows = [];

    if (Array.isArray(tableDataOrMarkdown)) {
      rows = tableDataOrMarkdown;
    } else if (typeof tableDataOrMarkdown === "string") {
      const rawLines = tableDataOrMarkdown.trim().split("\n");
      for (const line of rawLines) {
        if (!line.includes("|")) continue;
        if (line.match(/^\|?\s*[-:]+[-| :]*\|?$/)) continue;
        const cols = line
          .split("|")
          .map((c) => c.trim())
          .filter((_, idx, arr) => (idx > 0 && idx < arr.length - 1) || arr.length <= 2);
        if (cols.length > 0) {
          rows.push(cols);
        }
      }
    }

    const ws = XLSX.utils.aoa_to_sheet(rows);
    const csv = XLSX.utils.sheet_to_csv(ws);
    const finalName = filename.endsWith(".csv") ? filename : `${filename}.csv`;
    downloadTextFile(finalName, csv, "text/csv;charset=utf-8;");
    return true;
  } catch (err) {
    console.error("CSV Export Error:", err);
    throw err;
  }
}

